name: Publish .net App

on:
  workflow_dispatch:
  push:
    branches:
    - master
    
env:
  AZURE_WEBAPP_NAME: AzDemosRepo
  AZURE_WEBPAPP_PACKAGE_LOCATION: "./publish"
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .net 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: Project Restore
        run: dotnet restore ./Az_Demos_Repo.csproj
        
      - name: Build
        run: dotnet build ./Az_Demos_Repo.csproj --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./Az_Demos_Repo.csproj --configuration Release --no-build --output '${{ env.AZURE_WEBPAPP_PACKAGE_LOCATION }}'

      - name: Deploy to Azure web app
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBPAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBPAPP_PACKAGE_LOCATION }}

      
   
